Repository Clariteia/minos_microservice_common, pull requests merged in 2021-05, with the labels that each got.

#151 #150 (select as asynciterator)
  minos/common/__init__.py
  minos/common/database.py
  minos/common/model/aggregate.py
  minos/common/repository/abc.py
  minos/common/repository/memory.py
  minos/common/repository/pg.py
  minos/common/setup.py
  tests/test_common/test_database.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
Labels: enhancement

#159 #148 (`created_at` on `aggregate_events` table)
  minos/common/database.py
  minos/common/repository/entries.py
  minos/common/repository/pg.py
  minos/common/setup.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
Labels: enhancement

#162 #155 (`snapshot` on `minos.common.MinosConfig`)
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_config.yml
Labels: enhancement

#166 #165 (mock `snapshot` config from `PostgresAsyncTestCase`)
  .github/workflows/python-tests.yml
  minos/common/testing.py
Labels: bug

#168 #167 (Extend `PostgreSqlMinosRepository.select(...)` filtering)
  minos/common/repository/pg.py
  tests/test_common/test_repository/test_pg.py
Labels: enhancement

#170 #164 (remove `.idea` directory)
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/minos_microservice_common.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: bug

#175 Move Event and Command Model into module
  minos/common/__init__.py
  minos/common/broker.py
  minos/common/command/__init__.py
  minos/common/command/command.py
  minos/common/event/__init__.py
  minos/common/event/event.py
  tests/test_common/test_broker.py
  tests/test_common/test_command/__init__.py
  tests/test_common/test_command/test_command.py
  tests/test_common/test_event/__init__.py
  tests/test_common/test_event/test_event.py
Labels: bug

#186 MinosConfig SAGA configuration
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_config.yml
Labels: enhancement

#189 Add items and queue to Saga MinosConfig
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_config.yml
Labels: bug

#196 #195 (Implement `avro_str`-like methods)
  minos/common/model/abc/model.py
  tests/test_common/test_model/test_abc/test_model.py
Labels: enhancement

#206 #205 (migrate to `orjson`)
  minos/common/protocol/json.py
  tests/test_common/test_protocol/test_avro.py
Labels: enhancement

#208 #207 (lmbd storage kwargs)
  minos/__init__.py
  minos/common/storage/__init__.py
  minos/common/storage/abc.py
  minos/common/storage/abstract.py
  minos/common/storage/lmdb.py
Labels: enhancement

#212 #211 (`Event` contains a list of `MinosModel` instances)
  minos/common/model/event.py
Labels: enhancement

#214 #213 (meta export)
  minos/common/__init__.py
Labels: miscellaneous

#217 #194 (improve typing)
  minos/common/importlib.py
  minos/common/model/command.py
  minos/common/model/command_reply.py
  tests/test_common/test_importlib.py
Labels: miscellaneous

#192 Update testing.py
  .github/workflows/python-tests.yml
  minos/common/testing.py
Labels: enhancement

#230 #229 (saga manager abc)
  minos/common/__init__.py
  minos/common/saga.py
  tests/test_common/test_saga.py
Labels: enhancement

#233 #218 (`minos.common.Command.reply_on: Optional[str]`)
  minos/common/model/command.py
  tests/test_common/test_model/test_command.py
  tests/test_common/test_model/test_command_reply.py
  tests/test_common/test_model/test_event.py
Labels: bug

#235 #234 (config `saga.storage`)
  minos/common/__init__.py
  minos/common/configuration/__init__.py
  minos/common/configuration/config.py
  minos/common/storage/lmdb.py
  pyproject.toml
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_storage/test_lmdb.py
  tests/test_config.yml
Labels: enhancement

#242 #240 saga manager kwargs
  minos/common/saga.py
  tests/test_common/test_saga.py
Labels: miscellaneous

#244 #236 (update gitignore)
  .gitignore
Labels: meta

#248 #246 (revert changes on `BaseBroker` and more)
  minos/common/injectors.py
  minos/common/model/aggregate.py
  minos/common/networks.py
  minos/common/repository/abc.py
  minos/common/repository/memory.py
  minos/common/saga.py
  minos/common/setup.py
  tests/test_common/test_database.py
  tests/test_common/test_injectors.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_model/test_aggregate_with_posgres.py
  tests/test_common/test_networks.py
  tests/test_common/test_saga.py
  tests/test_common/test_setup.py
Labels: enhancement

#264 #263 (async `MinosSagaExecution.run`)
  minos/common/saga.py
  tests/test_common/test_injectors.py
  tests/test_common/test_networks.py
  tests/test_common/test_saga.py
  tests/utils.py
Labels: enhancement

#253 ISSUE #252
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_configuration/test_config_parameterized.py
  tests/test_common/test_configuration/test_config_with_env.py
Labels: refactor

#278 #273 (redefine `minos.common.Command` and `minos.common.CommandReply` attributes)
  minos/common/model/abc/model.py
  minos/common/model/command.py
  minos/common/model/command_reply.py
  minos/common/model/event.py
  tests/test_common/test_model/test_command.py
  tests/test_common/test_model/test_command_reply.py
  tests/test_common/test_saga.py
Labels: enhancement

#281 Initial docs
  AUTHORS.md
  CONTRIBUTING.md
  README.md
  RUNTHETESTS.md
  SETUP.md
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/readme.rst
  docs/runthetests.rst
  docs/usage.rst
  minos/common/configuration/config.py
  minos/common/repository/pg.py
  poetry.lock
  pyproject.toml
Labels: documentation
