Repository Clariteia/minos_microservice_common, pull requests merged in 2021-08, with the labels that each got.

#472 #402 (Refactor `RepositoryAction` into `AggregateAction`)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/aggregate/__init__.py
  minos/common/model/declarative/aggregate/actions.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/repository/__init__.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/builders.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_actions.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_declarative/test_networks.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
Labels: enhancement

#476 #475 (Add `UUID_REGEX`)
  minos/common/__init__.py
  minos/common/constants.py
  tests/test_common/test_constants.py
Labels: enhancement

#474 #466 (Fix database concurrency issues)
  minos/common/database/abc.py
  minos/common/database/pool.py
  minos/common/repository/pg.py
  minos/common/setup.py
  tests/test_common/test_database/__init__.py
  tests/test_common/test_database/test_abc.py
  tests/test_common/test_database/test_pool.py
  tests/test_common/test_setup.py
Labels: enhancement

#477 UUID regex pattern - issue #475
  tests/test_common/test_constants.py
Labels: refactor

#473 Add `User` to `Command` - ISSUE #395
  minos/common/model/declarative/networks.py
  tests/test_common/test_model/test_declarative/test_networks.py
Labels: enhancement

#482 #481 (Add support for `Decimal` and `memoryview`)
  minos/common/model/serializers/avro_data_encoder.py
  tests/test_common/test_model/test_serializers/test_avro_data_encoder.py
Labels: enhancement

#486 #483 (Accept positional arguments on `Model` building from `minos.common.ModelType`)
  minos/common/model/abc.py
  minos/common/model/declarative/abc.py
  minos/common/model/dynamic/abc.py
  minos/common/model/dynamic/dto.py
  minos/common/model/types/model_types.py
  tests/test_common/test_model/test_dynamic/test_dto.py
Labels: enhancement

#495 Add decompose method to minos.common.AggregateDiff
  minos/common/model/declarative/aggregate/diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
Labels: enhancement

#490 #489 (Allow passing type hints as named arguments on `ModelType.build`)
  minos/common/model/serializers/avro_schema_decoder.py
  minos/common/model/types/model_types.py
  tests/test_common/test_model/test_serializers/test_avro_schema_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_encoder.py
  tests/test_common/test_model/test_types/test_comparators.py
  tests/test_common/test_model/test_types/test_model_types.py
Labels: enhancement

#492 #479 (now `MinosSetup.from_config` also accepts `Path`)
  minos/common/setup.py
  tests/test_common/test_setup.py
Labels: enhancement

#494 #493 (Fix deadlocks related with `PostgreSqlSnaphot.get` and async iterators)
  minos/common/database/abc.py
  minos/common/repository/abc.py
  minos/common/repository/pg.py
  minos/common/snapshot/pg/builders.py
  minos/common/snapshot/pg/snapshot.py
  tests/test_common/test_snapshots/test_pg/test_snapshots.py
Labels: bug

#500 Update model.py
  minos/common/model/declarative/aggregate/model.py
Labels: enhancement

#507 Create Entity class
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/declarative/aggregate/ref.py
  minos/common/model/declarative/entities.py
  tests/test_common/test_model/test_declarative/test_entities.py
Labels: enhancement

#509 #508 (fix `minos.common.AvroDataEncoder` and inheritance bug)
  minos/common/model/serializers/avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
Labels: enhancement

#504 #501 (Rename `AggregateAction` as `Action`)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/actions.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/aggregate/__init__.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  tests/test_common/test_model/test_actions.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_actions.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_declarative/test_networks.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
Labels: enhancement

#520 #519 (Stop using `typing.Generic` when not needed)
  minos/common/__init__.py
  minos/common/database/pool.py
  minos/common/model/__init__.py
  minos/common/model/abc.py
  minos/common/model/declarative/abc.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/abc.py
  minos/common/model/dynamic/bucket.py
  minos/common/model/types/__init__.py
  minos/common/model/types/builders.py
  minos/common/model/types/comparators.py
  minos/common/model/types/data_types.py
  minos/common/model/types/model_types.py
  minos/common/setup.py
  tests/test_common/test_model/test_types/test_data_types.py
Labels: bug

#522 #521 (Support for `typing.Generic` and `minos.common.ModelType`)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/abc.py
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/serializers/avro_schema_encoder.py
  minos/common/model/types/__init__.py
  minos/common/model/types/builders.py
  minos/common/model/types/comparators.py
  minos/common/model/types/generics.py
  minos/common/model/types/model_refs.py
  minos/common/model/types/model_types.py
  tests/model_classes.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_abc/test_common.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_encoder.py
  tests/test_common/test_model/test_types/test_comparators.py
Labels: enhancement

#529 #528 (`kwargs` propagation over `PostgreSqlSnapshot`)
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/snapshot/entries.py
  minos/common/snapshot/pg/builders.py
  minos/common/snapshot/pg/snapshot.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_posgres.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_postgresql.py
  tests/test_common/test_snapshots/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_snapshots.py
Labels: bug

#506 #503 (Add `EntitySet`)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/entities.py
  tests/test_common/test_model/test_declarative/test_entities.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/utils.py
Labels: enhancement

#512 #511 (Add `EntitySetDiff` class)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/entities.py
  tests/test_common/test_model/test_declarative/test_entities.py
Labels: enhancement

#518 #514 (Add `minos.common.ValueObjectSet`)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/value_object.py
  minos/common/model/declarative/value_objects.py
  tests/test_common/test_model/test_declarative/test_value_object.py
  tests/value_objects.py
Labels: enhancement

#525 ValueObjectSetDiff
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/declarative/__init__.py
  minos/common/model/declarative/value_objects.py
  tests/test_common/test_model/test_declarative/test_value_object.py
Labels: enhancement

#516 #515 (integrate `EntitySetDiff` with `AggregateDiff`)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/__init__.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/declarative/entities.py
  minos/common/model/declarative/value_objects.py
  minos/common/model/dynamic/__init__.py
  minos/common/model/dynamic/bucket.py
  minos/common/model/dynamic/diff.py
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/serializers/avro_schema_encoder.py
  minos/common/model/types/model_types.py
  minos/common/repository/entries.py
  minos/common/snapshot/pg/builders.py
  tests/aggregate_classes.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_postgresql.py
  tests/test_common/test_model/test_declarative/test_networks.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_snapshots.py
Labels: enhancement

#534 #505 (`minos.common.Model` inherits from `collections.abc.Mapping`)
  minos/common/model/abc.py
  minos/common/model/declarative/abc.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/diff.py
  tests/test_common/test_model/test_abc.py
  tests/test_common/test_model/test_declarative/test_abc/test_common.py
Labels: enhancement

#539 #537 (Fix bug related with `getitem`, `setitem`, `getattr` and `setattr`)
  minos/common/model/abc.py
  tests/test_common/test_model/test_declarative/test_abc/test_common.py
Labels: bug

#542 #540 - Add `created_at` and `updated_at` to `Aggregate`
  minos/common/__init__.py
  minos/common/datetime.py
  minos/common/exceptions.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/repository/entries.py
  minos/common/repository/memory.py
  minos/common/snapshot/entries.py
  minos/common/snapshot/pg/builders.py
  tests/test_common/test_datetime.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_postgresql.py
  tests/test_common/test_model/test_declarative/test_networks.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_encoder.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_snapshots.py
  tests/utils.py
Labels: enhancement

#541 #536,#538 - Fix bugs related with `minos.common.FieldDiffContainer`
  minos/common/__init__.py
  minos/common/datetime.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/diff.py
  tests/test_common/test_datetime.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_repository/test_entries.py
Labels: bug

#547 #546 - Only store `Aggregate` changes
  minos/common/model/declarative/aggregate/model.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
Labels: enhancement

#545 #544 - Rename `minos.common.constants` as `minos.common.uuid`
  minos/common/__init__.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/repository/memory.py
  minos/common/repository/pg.py
  minos/common/uuid.py
  tests/test_common/test_uuid.py
Labels: miscellaneous

#550 #549 - fix bugs from latest version
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/serializers/avro_data_encoder.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_data_encoder.py
Labels: bug

#554 #553 - Implement `ModelType` inequalitites
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/types/comparators.py
  minos/common/model/types/model_types.py
  tests/test_common/test_model/test_types/test_comparators.py
  tests/test_common/test_model/test_types/test_model_types.py
Labels: enhancement

#555 #552 - Add generics to `MinosSagaManager`
  minos/common/saga.py
  minos/common/setup.py
Labels: miscellaneous

#557 #556 - Remove `saga.items` from `MinosConfig`
  minos/common/__init__.py
  minos/common/configuration/__init__.py
  minos/common/configuration/config.py
  tests/test_config.yml
Labels: enhancement

#559 #558 - Add `service.aggregate` to `MinosConfig`
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_config.yml
Labels: enhancement
