Repository Clariteia/minos_microservice_common, pull requests merged in 2021-09, with the labels that each got.

#561 #560 - hotfixes
  minos/common/launchers.py
  minos/common/model/types/builders.py
  tests/test_common/test_launchers.py
  tests/test_common/test_model/test_types/test_builders.py
Labels: bug

#568 #567 - `avro_data` minor refactor
  minos/common/model/abc.py
  minos/common/model/fields.py
  minos/common/model/serializers/avro_data_encoder.py
  tests/test_common/test_model/test_fields.py
Labels: enhancement

#573 #572 (`avro`'s record schema patch)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/abc.py
  minos/common/model/fields.py
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/serializers/avro_schema_encoder.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_model/test_dynamic/test_dto.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_encoder.py
Labels: enhancement

#571 #563,#569 - Store `Snapshot` `data` in `json`
  minos/common/__init__.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/queries.py
  minos/common/setup.py
  minos/common/snapshot/__init__.py
  minos/common/snapshot/abc.py
  minos/common/snapshot/entries.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/__init__.py
  minos/common/snapshot/pg/abc.py
  minos/common/snapshot/pg/builders.py
  minos/common/snapshot/pg/queries.py
  minos/common/snapshot/pg/snapshot.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_not_provided.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_postgresql.py
  tests/test_common/test_queries.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_queries.py
  tests/test_common/test_snapshots/test_pg/test_snapshots.py
  tests/utils.py
Labels: enhancement

#579 #578 - Added type to discovery.
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_configuration/test_config_parameterized.py
  tests/test_common/test_configuration/test_config_with_env.py
  tests/test_config.yml
Labels: enhancement

#575 #574 - Refactor `PostgreSqlSnapshot`
  minos/common/__init__.py
  minos/common/snapshot/__init__.py
  minos/common/snapshot/abc.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/__init__.py
  minos/common/snapshot/pg/api.py
  minos/common/snapshot/pg/readers.py
  minos/common/snapshot/pg/writers.py
  tests/test_common/test_snapshots/test_pg/test_api.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
  tests/test_common/test_snapshots/test_pg/test_writers.py
  tests/utils.py
Labels: enhancement

#582 #581 - Stop using `NoReturn` when `None` is returned
  minos/common/configuration/config.py
  minos/common/database/abc.py
  minos/common/injectors.py
  minos/common/model/abc.py
  minos/common/model/declarative/abc.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/declarative/entities.py
  minos/common/model/declarative/value_objects.py
  minos/common/model/fields.py
  minos/common/model/types/model_refs.py
  minos/common/networks.py
  minos/common/pools.py
  minos/common/storage/abc.py
  minos/common/storage/lmdb.py
  minos/common/testing.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_setup.py
  tests/utils.py
Labels: miscellaneous

#590 #588 - Fix bug related with dependency injections.
  minos/common/database/abc.py
  minos/common/injectors.py
  minos/common/launchers.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/setup.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/abc.py
  minos/common/snapshot/pg/readers.py
  minos/common/snapshot/pg/writers.py
  tests/test_common/test_database/test_abc.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_not_provided.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_setup.py
  tests/test_common/test_snapshots/test_pg/test_abc.py
Labels: bug

#591 #587 - Remove `events` section from `MinosConfig`
  minos/common/__init__.py
  minos/common/configuration/__init__.py
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_configuration/test_config_parameterized.py
  tests/test_common/test_configuration/test_config_with_env.py
  tests/test_config.yml
Labels: enhancement

#585 #584 - Support `typing.Optional` by `ModelRefExtractor`.
  minos/common/model/serializers/avro_schema_decoder.py
  minos/common/model/types/builders.py
  minos/common/model/types/model_refs.py
  tests/test_common/test_model/test_serializers/test_avro_schema_decoder.py
  tests/test_common/test_model/test_types/test_model_refs.py
Labels: enhancement

#592 #312 - Add `minos.common.Field` support to `timedelta`
  minos/common/model/serializers/avro_data_decoder.py
  minos/common/model/serializers/avro_data_encoder.py
  minos/common/model/serializers/avro_schema_decoder.py
  minos/common/model/serializers/avro_schema_encoder.py
  minos/common/model/serializers/constants.py
  tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_data_encoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_decoder.py
  tests/test_common/test_model/test_serializers/test_avro_schema_encoder.py
  tests/test_common/test_protocol/test_avro/test_base.py
Labels: enhancement
