Repository Clariteia/minos_microservice_common, pull requests merged in 2021-06, with the labels that each got.

#284 #267 (remove `minos.common.MinosDependencyInjector`)
  Makefile
  minos/common/__init__.py
  minos/common/injectors.py
  setup.cfg
  tests/test_common/test_injectors.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_model/test_aggregate_with_posgres.py
Labels: miscellaneous

#290 #287 (refactor `minos.common.messages` module)
  minos/common/__init__.py
  minos/common/messages.py
  minos/common/messages/__init__.py
  minos/common/messages/request.py
  minos/common/messages/response.py
  tests/test_common/test_messages.py
  tests/test_messages.py
Labels: enhancement

#293 #292 (improve `import_module` and `classname` functions)
  minos/common/importlib.py
  tests/test_common/test_importlib.py
Labels: enhancement

#295 #294 (Fix bug related with database tear down)
  minos/common/testing.py
Labels: bug

#296 #285 (improve aggregate type hinting)
  minos/common/model/aggregate.py
Labels: meta

#297 #291 (remove logs module)
  minos/common/logs.py
  minos/common/model/abc/fields.py
  minos/common/model/abc/model.py
  minos/common/protocol/avro/messages.py
Labels: miscellaneous

#300 #299 (Migrate `EntrypointLauncher`, `DependencyInjector` and `Service` from microservice)
  minos/common/__init__.py
  minos/common/injectors.py
  minos/common/launchers.py
  minos/common/services.py
  tests/test_common/test_injectors.py
  tests/test_common/test_launchers.py
  tests/test_common/test_service.py
  tests/utils.py
Labels: enhancement

#305 Recover avro schema
  minos/common/protocol/avro/base.py
  tests/test_common/test_protocol/test_avro/test_base.py
Labels: enhancement

#311 #268 (publish `minos.common.Aggregate` changes over `minos.common.MinosBroker`)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model/test_avro.py
  tests/test_common/test_model/test_aggregate/test_base.py
  tests/test_common/test_model/test_aggregate/test_broker.py
  tests/test_common/test_model/test_aggregate/test_non_provided.py
  tests/test_common/test_model/test_aggregate/test_with_posgres.py
  tests/test_common/test_networks.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_service.py
  tests/utils.py
Labels: enhancement

#310 #269 (`minos.common.Aggregate` refactor at `update` and `delete` methods)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_messages.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model/test_avro.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_model/test_aggregate/__init__.py
  tests/test_common/test_model/test_aggregate/test_base.py
  tests/test_common/test_model/test_aggregate/test_broker.py
  tests/test_common/test_model/test_aggregate/test_not_provided.py
  tests/test_common/test_model/test_aggregate/test_with_posgres.py
  tests/test_common/test_model/test_command.py
  tests/test_common/test_model/test_command_reply.py
  tests/test_common/test_model/test_event.py
  tests/test_common/test_networks.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_saga.py
  tests/test_common/test_service.py
  tests/utils.py
Labels: miscellaneous

#313 Recompose ModelField instances from avro_schema
  minos/common/model/abc/fields.py
  minos/common/model/abc/types.py
  tests/test_common/test_model/test_abc/test_fields.py
Labels: enhancement

#307 #289 (Accept `UUID` type on `minos.common.ModelField`)
  minos/common/model/abc/fields.py
  minos/common/model/abc/types.py
  tests/model_classes.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model/test_avro.py
Labels: enhancement

#308 #288 (Accept `date`, `time` and `datetime` types on `minos.common.ModelField`)
  minos/common/model/abc/fields.py
  minos/common/model/abc/types.py
  tests/test_common/test_model/test_abc/test_fields.py
Labels: enhancement

#319 Refactor minos.common.model.abc.fields #316
  minos/common/model/abc/__init__.py
  minos/common/model/abc/fields.py
  minos/common/model/abc/fields/__init__.py
  minos/common/model/abc/fields/avro_data_builder.py
  minos/common/model/abc/fields/caster.py
  minos/common/model/abc/fields/common.py
  minos/common/model/abc/fields/fields.py
  minos/common/model/abc/fields/model_builder.py
  minos/common/model/abc/fields/schema_builder.py
  minos/common/model/abc/model.py
Labels: enhancement

#322 #320 (simplify `repository` class names)
  minos/common/__init__.py
  minos/common/model/aggregate.py
  minos/common/repository/__init__.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/repository/memory.py
  minos/common/repository/pg.py
  tests/test_common/test_model/test_aggregate/test_base.py
  tests/test_common/test_model/test_aggregate/test_with_posgres.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
  tests/utils.py
Labels: miscellaneous

#318 #315 (Define `MinosSnapshot` base class)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  minos/common/repository/entries.py
  minos/common/snapshot/__init__.py
  minos/common/snapshot/abc.py
  minos/common/snapshot/entries.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/__init__.py
  minos/common/snapshot/pg/abc.py
  minos/common/snapshot/pg/builders.py
  minos/common/snapshot/pg/snapshot.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model/test_avro.py
  tests/test_common/test_model/test_aggregate/test_base.py
  tests/test_common/test_model/test_aggregate/test_broker.py
  tests/test_common/test_model/test_aggregate/test_not_provided.py
  tests/test_common/test_model/test_aggregate/test_with_posgres.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/__init__.py
  tests/test_common/test_snapshots/test_entries.py
  tests/test_common/test_snapshots/test_pg/__init__.py
  tests/test_common/test_snapshots/test_pg/test_abc.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
  tests/utils.py
Labels: enhancement

#326 #325 (equality and `fields` ordering on `minos.common.MinosModel`)
  minos/common/model/abc/model.py
Labels: enhancement

#306 #271 (Rename `insert` as `create` in `minos.common.MinosRepositoryAction`)
  minos/common/model/declarative/aggregate/model.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/repository/pg.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
Labels: miscellaneous

#330 #84 (`minos.common.AggregateDiff` integration with `minos.common.MinosRepository` and `minos.common.MinosSnapshot`)
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/abc.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/builders.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
Labels: enhancement

#321 #309 (create `minos.common.DataTransferObject` class)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/abc.py
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/__init__.py
  minos/common/model/dynamic/abc.py
  minos/common/model/dynamic/dto.py
  minos/common/model/fields/__init__.py
  minos/common/model/fields/avro_data_decoder.py
  minos/common/model/fields/avro_data_encoder.py
  minos/common/model/fields/avro_schema_decoder.py
  minos/common/model/fields/avro_schema_encoder.py
  minos/common/model/fields/fields.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/snapshot/memory.py
  minos/common/snapshot/pg/builders.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_dynamic/test_abc.py
  tests/test_common/test_model/test_dynamic/test_dto.py
  tests/test_common/test_model/test_fields/test_avro_data_decoder.py
  tests/test_common/test_model/test_fields/test_avro_schema_decoder.py
  tests/test_common/test_model/test_fields/test_avro_schema_encoder.py
  tests/test_common/test_model/test_fields/test_fields.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
Labels: enhancement

#336 #272 (Remove implicit `object` inheritance)
  minos/common/meta.py
  minos/common/model/fields/avro_data_decoder.py
  minos/common/model/fields/avro_data_encoder.py
  minos/common/model/fields/avro_schema_decoder.py
  minos/common/model/fields/avro_schema_encoder.py
  minos/common/repository/entries.py
  minos/common/snapshot/entries.py
Labels: miscellaneous

#334 #333 (Send `AggregateDiff` instances as events instead of `Aggregate` ones)
  minos/common/model/declarative/aggregate/diff.py
  minos/common/model/declarative/aggregate/model.py
  minos/common/model/dynamic/diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
  tests/test_common/test_model/test_dynamic/test_diff.py
Labels: enhancement

#332 #331 (improve `Aggregate` deletion behaviour on `Snapshot`)
  minos/common/exceptions.py
  minos/common/snapshot/entries.py
  minos/common/snapshot/pg/abc.py
  minos/common/snapshot/pg/builders.py
  minos/common/snapshot/pg/snapshot.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
Labels: enhancement

#342 Issue 341 discovery service conf
  minos/common/configuration/config.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_configuration/test_config_parameterized.py
  tests/test_common/test_configuration/test_config_with_env.py
  tests/test_config.yml
Labels: enhancement

#339 #337 (Integrate `minos.common.DataTransferObject` with `minos.common.Event`)
  minos/common/__init__.py
  minos/common/model/__init__.py
  minos/common/model/abc.py
  minos/common/model/declarative/abc.py
  minos/common/model/declarative/event.py
  minos/common/model/dynamic/__init__.py
  minos/common/model/dynamic/abc.py
  minos/common/model/dynamic/bucket.py
  minos/common/model/dynamic/diff.py
  minos/common/model/dynamic/dto.py
  minos/common/model/fields/__init__.py
  minos/common/model/fields/avro_data_decoder.py
  minos/common/model/fields/avro_schema_encoder.py
  minos/common/model/fields/fields.py
  minos/common/model/fields/type_hint_builder.py
  minos/common/model/fields/type_hint_comparator.py
  minos/common/model/types.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_event.py
  tests/test_common/test_model/test_dynamic/test_abc.py
  tests/test_common/test_model/test_dynamic/test_bucket.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_model/test_dynamic/test_dto.py
  tests/test_common/test_model/test_fields/test_type_hint_builder.py
  tests/test_common/test_model/test_fields/test_type_hint_comparator.py
  tests/test_common/test_model/test_types.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
Labels: enhancement

#343 #314 (Add `minos.common.Aggregate.save` method)
  minos/common/model/declarative/aggregate/model.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
Labels: enhancement

#345 #344 (Simplify `minos.common.Aggregate` constructor)
  minos/common/model/declarative/aggregate/model.py
  tests/test_common/test_model/test_declarative/test_abc/test_avro.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_not_provided.py
  tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_posgres.py
  tests/test_common/test_model/test_dynamic/test_diff.py
  tests/test_common/test_model/test_fields/test_fields.py
  tests/test_common/test_snapshots/test_entries.py
  tests/test_common/test_snapshots/test_pg/test_builders.py
  tests/test_common/test_snapshots/test_pg/test_readers.py
Labels: enhancement

#348 #347 (Fix `DependencyInjector`)
  minos/common/injectors.py
  minos/common/launchers.py
  minos/common/setup.py
  minos/common/storage/lmdb.py
  tests/utils.py
Labels: bug

#356 #353 (load injections and services from config)
  minos/common/configuration/config.py
  minos/common/injectors.py
  minos/common/launchers.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_injectors.py
  tests/test_common/test_launchers.py
Labels: enhancement

#355 #354 (Fix bug related with `avro_data` and `datetime`'s timezones)
  minos/common/configuration/config.py
  minos/common/injectors.py
  minos/common/launchers.py
  minos/common/model/fields/avro_data_encoder.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_injectors.py
  tests/test_common/test_launchers.py
Labels: bug

#363 #362 (improve exception messages on `minos.common.AvroDataDecoder`)
  minos/common/model/fields/avro_data_decoder.py
Labels: miscellaneous

#365 #364 (`minos.common.FieldsDiff.from_difference` now accepts not hashable `ModelField` values)
  minos/common/model/dynamic/diff.py
  tests/test_common/test_model/test_dynamic/test_diff.py
Labels: bug

#367 #366 (implement `__str__` on models)
  minos/common/model/abc.py
  minos/common/model/dynamic/dto.py
  minos/common/model/fields/fields.py
  tests/test_common/test_model/test_declarative/test_abc/test_common.py
  tests/test_common/test_model/test_dynamic/test_dto.py
  tests/test_common/test_model/test_fields/test_fields.py
Labels: enhancement
