Repository Clariteia/minos_microservice_common, pull requests merged in 2021-04, with the labels that each got.

#15 Hotfix: Run CI after every push
  .github/workflows/python-tests.yml
Labels: bug

#17 Issue #11 (support dict by model field)
  minos/common/model/fields.py
  tests/test_common/__init__.py
  tests/test_common/test_model/__init__.py
  tests/test_common/test_model/test_fields.py
Labels: enhancement

#14 Issue #9 (optional values for ModelField)
  minos/common/model/fields.py
  tests/modelClasses.py
  tests/test_common/__init__.py
  tests/test_common/test_model/__init__.py
  tests/test_common/test_model/test_fields.py
Labels: enhancement

#20 Issue #19 (rename aggregate as model)
  minos/common/model/__init__.py
  minos/common/model/model.py
  tests/test_aggregate_model.py
  tests/test_common/test_model/test_model.py
Labels: bug

#18 Issue #11 (support dict by model field)
  minos/common/model/fields.py
  tests/test_common/test_model/test_fields.py
Labels: enhancement

#31 Issue #30 (required field exception)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/fields.py
  minos/common/model/model.py
  minos/common/model/types.py
  tests/modelClasses.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#36 Issue #34 (refactor `minos.common.ModelField` value setter)
  minos/common/model/fields.py
  tests/modelClasses.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#35 Issue #28 (custom attribute validators)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/fields.py
  minos/common/model/model.py
  tests/modelClasses.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#33 Issue #29 (custom attribute parsers)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/__init__.py
  minos/common/model/fields.py
  minos/common/model/model.py
  tests/modelClasses.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#65 #39 (avro encoded and decoder)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/model.py
  minos/common/protocol/avro.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#41 #40 (avro data preparation)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/__init__.py
  minos/common/model/fields.py
  minos/common/model/model.py
  minos/common/model/types.py
  minos/common/protocol/avro.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#69 #52 (dictionary keys must be strings)
  minos/common/model/fields.py
  tests/modelClasses.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#63 #62 (base broker service class)
  minos/__init__.py
  minos/common/broker.py
  tests/test_broker.py
Labels: enhancement

#68 #53 (refactor model-field class)
  minos/common/exceptions.py
  minos/common/model/fields.py
  minos/common/model/model.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_fields.py
  tests/test_common/test_model/test_model.py
Labels: enhancement

#81 #57 (repository class)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  minos/common/repository/__init__.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/repository/memory.py
  tests/aggregate_classes.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_repository/__init__.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
Labels: enhancement

#99 #92 (extract classname)
  minos/common/__init__.py
  minos/common/importlib.py
  minos/common/model/abc/model.py
  minos/common/model/aggregate.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  tests/test_common/test_importlib.py
  tests/test_common/test_model/test_abc/test_model.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_importlib.py
Labels: enhancement

#90 #88 (postgresql repository)
  .github/workflows/python-tests.yml
  minos/common/__init__.py
  minos/common/model/abc/model.py
  minos/common/model/aggregate.py
  minos/common/repository/__init__.py
  minos/common/repository/abc.py
  minos/common/repository/entries.py
  minos/common/repository/memory.py
  minos/common/repository/pg.py
  setup.cfg
  setup.py
  tests/database_testcase.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_repository/test_entries.py
  tests/test_common/test_repository/test_memory.py
  tests/test_common/test_repository/test_pg.py
Labels: enhancement

#105 #104 (custom exception)
  minos/common/__init__.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  minos/common/repository/entries.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_repository/test_entries.py
Labels: enhancement

#101 #86 (hotfix modelfref avro schema)
  minos/common/meta.py
  minos/common/model/abc/fields.py
  minos/common/model/abc/model.py
  minos/common/model/aggregate.py
  minos/common/repository/entries.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model.py
  tests/test_common/test_model/test_aggregate.py
Labels: bug

#115 Minos Config Queue Retry parameter
  minos/common/configuration/config.py
  tests/test_config.py
  tests/test_config.yaml
Labels: enhancement

#122 Broker Base classes for Event/Command
  minos/common/broker.py
Labels: enhancement

#119 #54 (migrate to fastavro)
  minos/common/protocol/avro.py
  setup.py
  tests/test_avro_encoder_decoder.py
  tests/test_common/test_protocol/__init__.py
  tests/test_common/test_protocol/test_avro.py
Labels: nice to have

#111 #103 (repository inject config)
  minos/common/__init__.py
  minos/common/configuration/config.py
  minos/common/exceptions.py
  minos/common/model/aggregate.py
  minos/common/repository/abc.py
  minos/common/repository/pg.py
  tests/test_common/test_configuration/__init__.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_exceptions.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_config.py
  tests/test_config.yaml
  tests/utils.py
Labels: enhancement

#129 #128 (Expose `minos.common.broker`)
  minos/common/__init__.py
  minos/common/broker.py
  tests/test_broker.py
Labels: enhancement

#134 #131 (abstract minos setup class)
  minos/common/__init__.py
  minos/common/repository/abc.py
  minos/common/repository/memory.py
  minos/common/setup.py
  tests/test_common/test_setup.py
Labels: enhancement

#116 #59 (ModelRef[T] = Union[T, int])
  minos/common/model/abc/fields.py
  tests/aggregate_classes.py
  tests/model_classes.py
  tests/test_common/test_model/test_abc/test_fields.py
  tests/test_common/test_model/test_abc/test_model.py
Labels: enhancement

#136 #132 (config env variables)
  .github/workflows/python-tests.yml
  minos/common/configuration/config.py
  minos/common/testing.py
  tests/database_testcase.py
  tests/test_common/test_configuration/test_config.py
  tests/test_common/test_model/test_aggregate.py
  tests/test_common/test_repository/test_pg.py
  tests/test_config.yml
Labels: enhancement

#145 #143 (recursive from avro bytes)
  minos/common/broker.py
  minos/common/meta.py
  minos/common/model/abc/fields.py
  minos/common/model/abc/model.py
  tests/test_broker.py
  tests/test_common/test_broker.py
  tests/test_common/test_model/test_abc/test_model.py
Labels: bug, enhancement

#154 #153 (unique identifier test database)
  minos/common/testing.py
Labels: bug
